### ISSUE TITLE
Delay when pressing the "Додати епізод" button

### ISSUE THREAD

**Issue by Lorg0n** [hikka-io/hikka-next#7]
https://github.com/olexh/hikka-next/assets/37798530/091150b5-16b0-4024-b09a-87649547aad6

_watch with sound_

As far as I understand, the front end waits for a response from the backend before visually updating the number on the screen. Wouldn't it be better to draw the number right away and then send the final decision to the server, so that visually no display delays occur?

**Comment by olexh** [comment]
Yes, it’s called optimistic updates. We really should improve UX for all update requests, but first of all I need to do a refactor of useMutation hooks to avoid more unmaintainable code in the future. Thanks for the feedback, I account it in the next updates

**Comment by olexh** [comment]
Added optimistic updates to profile block on home page and watch stats block on anime page. Closing the issue.

https://github.com/hikka-io/hikka-next/assets/29921082/b1a86273-3d0f-404f-9a73-4dd7e2cbc92e

https://github.com/hikka-io/hikka-next/assets/29921082/62bc247b-ecc0-4f05-a82c-ddb152a45090

**Comment by Lorg0n** [comment]
Дякую!
